### ISSUE TITLE
impossible condition in arm.cpp

### ISSUE THREAD

**Issue by malocharo** [atim-radiocommunications/armapi#5]
Hi,
there is an impossible condition line 1672 of the file arm.cpp

`//Check if out of range
		if((nbFrame > 15) && (nbFrame < -15))
return ARM_ERR_PARAM_OUT_OF_RANGE;`

nbFrame cannot be higher than 15 and lower than -15 at the same time.
I suppose it should be this instead:

`//Check if out of range
		if((nbFrame > 15) || (nbFrame < -15))
return ARM_ERR_PARAM_OUT_OF_RANGE;`

Thank you anyway for this API

**Comment by antoine163** [comment]
Exactly, Thank for your feedback.
